spring:
  datasource:
    platform: mariadb
    url: jdbc:mariadb://localhost:3306/hello-jpa-ex1
    driver-class-name: org.mariadb.jdbc.Driver
    username: ex1
    password: "1111"
    hikari:      
      pool-name: ex1-hikari-pool
      maximum-pool-size: 10
      connection-init-sql: select 1
  jpa:
    database: mysql
    #InnoDB \uC124\uC815
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #\uAE30\uBCF8\uC124\uC815, MyISAM
    #database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #physical-strategy: com.skcc.jpa.UpperSnakeCasePhysicalNamingStrategy
    show-sql: true
